apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-webapp-production
  namespace: argocd
  labels:
    environment: production
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: pr-reviewer-alerts
    notifications.argoproj.io/subscribe.on-health-degraded.slack: pr-reviewer-alerts
spec:
  project: default
  
  source:
    repoURL: https://github.com/nchouser54/aws-agentic-ai-bedrock.git
    targetRevision: main  # Production from main branch
    path: helm/chatbot-webapp
    helm:
      valueFiles:
        - values.yaml
        - examples/values-production.yaml
      values: |
        webapp:
          image:
            repository: REPLACE_WITH_ECR_URL/chatbot-webapp
            tag: "REPLACE_WITH_VERSION"  # e.g., v1.2.3 (specific version, NOT latest)
          
          replicaCount: 3  # Higher for production
        
        config:
          chatbotUrl: "REPLACE_WITH_PROD_API_URL"
        
        ingress:
          enabled: true
          className: alb
          annotations:
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/certificate-arn: REPLACE_WITH_ACM_CERT_ARN
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
            alb.ingress.kubernetes.io/ssl-redirect: '443'
            # Add WAF for production
            alb.ingress.kubernetes.io/wafv2-acl-arn: REPLACE_WITH_WAF_ACL_ARN
          hosts:
            - host: chatbot.REPLACE_WITH_DOMAIN
              paths:
                - path: /
                  pathType: Prefix
          tls:
            certificateArn: REPLACE_WITH_ACM_CERT_ARN
        
        autoscaling:
          enabled: true
          minReplicas: 3
          maxReplicas: 20
          targetCPUUtilizationPercentage: 70
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Pod disruption budget for HA
        podDisruptionBudget:
          enabled: true
          minAvailable: 2
        
        # Network policies for security
        networkPolicy:
          enabled: true
          policyTypes:
            - Ingress
            - Egress
  
  destination:
    server: https://kubernetes.default.svc
    namespace: chatbot-webapp-production
  
  syncPolicy:
    # MANUAL sync for production (more control)
    automated:
      prune: false  # Don't auto-delete resources in prod
      selfHeal: true  # Auto-heal if someone manually changes
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 5m
  
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # HPA manages replicas
